name: "💻 Reunião"
description: "Template para organizar reuniões com clientes ou equipe."
title: "[Meet] "
labels: ["meet"]

body:
  - type: input
    id: data
    attributes:
      label: "📅 Data"
      description: "Informe a data da reunião."
      placeholder: "Ex: 20/02/2025"
    validations:
      required: true

  - type: input
    id: hora
    attributes:
      label: "⏰ Horário"
      description: "Informe o horário da reunião."
      placeholder: "Ex: 15:00"
    validations:
      required: true

  - type: input
    id: local
    attributes:
      label: "📍Local"
      description: "Informe o Local da reunião."
      placeholder: "Ex: Av. Paulista"
    validations:
      required: true

  - type: dropdown
    id: tipo
    attributes:
      label: "📝 Tipo de Reunião"
      description: "Selecione o tipo de reunião."
      multiple: true
      options:
        - Com equipe
        - Com cliente
        - Com orientador
    validations:
      required: true

  - type: textarea
    id: objetivo
    attributes:
      label: "📋 objetivos da Reunião"
      description: "Liste os objetivos a serem discutidos."
      placeholder: "Ex: Feedback do cliente, planejamento de features, etc."

  - type: textarea
    id: pauta
    attributes:
      label: "📂 Pauta da Reunião"
      description: "Liste os tópicos a serem discutidos."
      placeholder: "Ex: Feedback do cliente, planejamento de features, etc."
