name: "Detect Movement to Review"

on:
  project_card:
    types: [moved]

jobs:
  detect-move:
    runs-on: ubuntu-latest
    steps:
      - name: Log Card Movement
        run: |
          echo "Card movido para a coluna: ${{ github.event.project_card.column_name }}"
          
          if [[ "${{ github.event.project_card.column_name }}" == "Review" ]]; then
            echo "O card foi movido para a coluna Review!"
          else
            echo "O card não foi movido para Review, ignorando."
          fi