name: Teste Projects API

on:
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  test-projects:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      projects: read  # Dá permissão para acessar os projetos
    steps:
      - name: Listar projetos do repositório
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/projects
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
